
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('items').del()
    .then(function () {
      // Inserts seed entries
      return knex('items').insert([
        {id: 1, name: 'Chocolate Cupcake', shop_id: 1, stock_qty: 6, steps: '{"1": "Preheat oven to 350 degrees F (175 degrees C). Line a muffin pan with paper or foil liners. Sift together the flour, baking powder, baking soda, cocoa and salt. Set aside.", "2": "In a large bowl, cream together the butter and sugar until light and fluffy. Add the eggs one at a time, beating well with each addition, then stir in the vanilla. Add the flour mixture alternately with the milk; beat well. Fill the muffin cups 3/4 full.", "3": "Bake for 15 to 17 minutes in the preheated oven, or until a toothpick inserted into the cake comes out clean. Frost with frosting when cool.", "5":"Box"}', category_id: 1, photo:'https://www.recipetineats.com/wp-content/uploads/2017/05/Chocolate-Cupcakes12-landscape.jpg'},
        {id: 2, name: 'Vanilla Cupcake', shop_id: 1, stock_qty: 6, steps: '{"1": "Preheat an oven to 350 degrees F (175 degrees C). Line a standard muffin tin with 12 paper cupcake liners. Combine flour, baking soda, and salt in a bowl; set aside.", "2": "Heat the butter and milk in a small saucepan over low heat until the butter has melted. Beat the sugar, eggs, egg yolk, and vanilla with an electric mixer in a large bowl until it has thickened slightly and is lighter in color.", "3": "Gradually beat in the flour mixture on low speed until just incorporated. Slowly pour in the hot milk, beating until just combined.", "4":"Divide batter evenly between cupcake liners. Bake until toothpick inserted into center comes out clean, about 20 minutes", "5":"Cool cupcakes in pan for 10 minutes. Transfer cupcakes to a cooling rack to cool completely.", "6":"Box"}', category_id: 1, photo:'http://redonline.cdnds.net/main/thumbs/2101/1372752153-vanilla-cupcakes-with-swirly-icing-mary-berry-s-cookery-course__square.jpg'},
        {id: 3, name: 'Strawberry Cake', shop_id: 1, stock_qty: 0, steps: '{"1": "Preheat oven to 350 degrees F. Lightly spray pans with non-stick spray.", "2": "Place the cake mix, jello, strawberries, oil, milk and eggs in a large bowl. Mix 3 minutes, stopping to scrap down sides of bowl a couple times. ", "3": "Divide the batter evenly among layer pans or pour into 9x13 inch pan. For 9x13 pan bake 28 minutes or until toothpick inserted in center comes out clean.", "4":"Remove cake and cool completely and frost.", "5":"Box"}', category_id: 2, photo:'https://tatyanaseverydayfood.com/wp-content/uploads/2015/10/Strawberry-Champagne-Cake.jpg'},
        {id: 4, name: 'Vanilla Cake', shop_id: 1, stock_qty: 7, steps: '{"1": "Preheat the oven to 350 degrees F. Butter two 9-inch-round cake pans and line the bottoms with parchment paper; butter the parchment and dust the pans with flour, tapping out the excess.", "2": "Whisk 3 cups flour, the baking powder and salt in a bowl until combined. Beat 2 sticks butter and the sugar in a large bowl with a mixer on medium-high speed until light and fluffy, about 3 minutes. Reduce the mixer speed to medium; beat in the eggs, one at a time.", "3": "Divide the batter between the prepared pans. Bake until the cakes are lightly golden on top and a toothpick inserted into the middle comes out clean, 30 to 35 minutes. Transfer to racks and let cool 10 minutes, then run a knife around the edge of the pans and turn the cakes out onto the racks to cool completely.", "4":"Remove the parchment. Trim the tops of the cakes with a long serrated knife to make them level, if desired. and Frost.", "5":"Box"}', category_id: 2, photo:'https://img1.southernliving.timeinc.net/sites/default/files/styles/4_3_horizontal_-_1200x900/public/image/2017/11/main/2546901_south_46_main-slice_0.jpg?itok=I0Ii0_8R'},
        {id: 5, name: 'Chocolate Cake', shop_id: 1, stock_qty: 10, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 2, photo:'http://www.trbimg.com/img-56b2a3d0/turbine/la-fo-proof-chocolate-cake-photos-012/'},
        {id: 6, name: 'Chocolate Cookies', shop_id: 1, stock_qty: 3, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 3, photo:'https://cdn-image.foodandwine.com/sites/default/files/styles/medium_2x/public/200902-xl-milk-chocolate-cookies-with-malted-cream.jpg?itok=Dt7vktKc'},
        {id: 7, name: 'SnickerDoodles', shop_id: 1, stock_qty: 2, steps: '{"1": "Cream the butter and sugar. Add egg, milk, and vanilla. Then add flour, baking powder, and salt.", "2": "Roll dough into 1.5-inch balls and roll them in cinnamon sugar.", "3": "Bake for 12 minutes at 375F.", "5":"Box"}', category_id: 3, photo:'https://sallysbakingaddiction.com/wp-content/uploads/2016/08/soft-caramel-snickerdoodles-1.jpg'},
        {id: 8, name: 'Sugar Cookies', shop_id: 1, stock_qty: 5, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 3, photo:'https://d2gk7xgygi98cy.cloudfront.net/4241-3-large.jpg'},
        {id: 9, name: 'Fruit Cakes', shop_id: 1, stock_qty: 3, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 2, photo:'http://foodandfam.com/wp-content/uploads/2014/06/Pound-Cake-Fruit.jpg'},
        {id: 10, name: 'Cutting Knife', shop_id: 1, stock_qty: 12, steps: '{"1": "Put a bow-tie around handle"}', category_id: 4, photo:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRBlHKM-_kAO5ajXvFWAX2xbzqvGbuyJflGSPxL1f6xmCJsAqaMUg'},
        {id: 11, name: 'Glazed Donuts', shop_id: 1, stock_qty: 5, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 6, photo:'https://i.pinimg.com/originals/4f/16/e5/4f16e51f7430ce9a7efe802e1c30439c.jpg'},
        {id: 12, name: 'Chocolate Donuts', shop_id: 1, stock_qty: 8, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 6, photo:'https://www.crunchycreamysweet.com/wp-content/uploads/2016/02/chocolate-donuts-1.jpg'},
        {id: 13, name: 'Creme Donuts', shop_id: 1, stock_qty: 14, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 6, photo:'http://www.marystestkitchen.com/wp-content/uploads/2017/08/ft-vegan-boston-cream-dooughnuts-bitten.jpg'},
        {id: 14, name: 'Blueberry Muffins', shop_id: 1, stock_qty: 17, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 5, photo:'https://static01.nyt.com/images/2016/05/03/dining/03COOKING-JORDANMARSHMUFFIN2/03COOKING-JORDANMARSHMUFFIN2-articleLarge.jpg'},
        {id: 15, name: 'Baklava', shop_id: 1, stock_qty: 13, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', photo:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRfVwtGpxSIJvox3Wb1Q4w0bfUKVmgGdGRTyDSLJSWYjP-w1leeFQ'},
        {id: 16, name: 'Candle Sticks', shop_id: 1, stock_qty: 40, steps: '{"1": "Add specified quantity to candle box"}', category_id: 4, photo:'https://i.pinimg.com/736x/79/75/3a/79753a77684486d7e22b9d8225e2d831--candle-holders-bees.jpg'},
        {id: 17, name: 'Banana Muffins', shop_id: 1, stock_qty: 11, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 5, photo:'https://www.mrbreakfast.com/images/755_muffins_with_banana.jpg'},
        {id: 18, name: 'Cinnamon Cookies', shop_id: 1, stock_qty: 9, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 3, photo:'https://www.recipegirl.com/wp-content/uploads/2013/02/Cinnamon-Vanilla-Monster-Cookies.jpg'},
        {id: 19, name: 'Raspberry Donuts', shop_id: 1, stock_qty: 4, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 6, photo:'https://avirtualvegan.com/wp-content/uploads/2017/02/Vegan-Raspberry-Donuts-6T.jpg'},
        {id: 20, name: 'Red Velvet Cupcakes', shop_id: 1, stock_qty: 6, steps: '{"1": "Get ingredients", "2": "Mix ingredients", "3": "Bake", "4":"Frost", "5":"Box"}', category_id: 1, photo:'https://www.recipethis.com/wp-content/uploads/Airfryer-Red-Velvet-Cupcake-Heaven.jpg'}
      ])
    })
    .then(() => {
      return knex.raw(
        "SELECT setval('items_id_seq', (SELECT MAX(id) FROM items));"
      );
    });
};
